wandb:
  project_name: "news_classifier"

model:
  vocab_size: 30522
  d_model: 256
  num_heads: 8
  d_ff: 512
  num_layers: 6
  num_classes: 4
  max_seq_len: 128
  dropout: 0.1
  tokenizer: "bert-base-uncased"

dataset:
  name: "fancyzhx/ag_news"
  cache_dir: "./data"

training:
  batch_size: 32
  epochs: 10
  lr: 5e-5
  checkpoint_dir_name: "checkpoints"
  checkpoint_interval: 2

test:
  batch_size: 32