defaults:
  - model
  - dataset
  - training
  - wandb

mode: "train"

training:
  batch_size: 32
  epochs: 10
  lr: 5e-5
  checkpoint_dir_name: "checkpoints"
  checkpoint_interval: 2

eval:
  batch_size: 32